# Travis CI Java documentation can be found in:
# https://docs.travis-ci.com/user/languages/java/

# We will use Ubuntu 20.04 (focal fossa). List of options:
# https://docs.travis-ci.com/user/reference/overview/#linux
dist: focal

# This enables the 'defaults' to test java applications:
language: java

# We test in jdk 11, a full list of available JDKs can be found at 
# https://docs.travis-ci.com/user/reference/xenial/#jvm-clojure-groovy-java-scala-support
jdk:
 - openjdk11
 
# before running junit, we need to install some optional portions of ant used to run the junit tests
before_install: 	
 - sudo apt-get install ant-optional
 

include: JUnit4

# We build the project and then run the JUnit tests; the build is successful if it compiles and the 
#tests pass 
script: 
 - ant build
 - ant test 
